let selectedFilm=null; let CATALOG={app:{currency:'HTG'},films:[]};
const $=s=>document.querySelector(s); const sections=['home','catalog','payment','access','watch'];
function show(id){sections.forEach(x=>{const e=document.getElementById(x);if(e)e.classList.toggle('hidden',x!==id)});window.scrollTo({top:0,behavior:'smooth'});}
function money(f){return `${Number(f.price||0).toLocaleString('fr-FR')} ${CATALOG.app.currency||'HTG'}`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function filmCard(f){return `<article class="card"><img class="poster" src="${esc(f.poster)}" alt="${esc(f.title)}"><div class="card-body"><span class="badge">${esc(f.status)}</span><h3>${esc(f.title)}</h3>${f.subtitle?`<div class="sub">${esc(f.subtitle)}</div>`:''}<div class="type">${esc(f.type)}</div><div class="desc">${esc(f.description)}</div><div class="price">${money(f)}</div><button class="btn" onclick="openFilm('${esc(f.id)}')">Acheter / Voir</button></div></article>`;}
function render(){ $('#catalogGrid').innerHTML=CATALOG.films.map(filmCard).join(''); $('#homeGrid').innerHTML=CATALOG.films.slice(0,3).map(filmCard).join(''); $('#paymentFilm').innerHTML=CATALOG.films.map(f=>`<option value="${esc(f.id)}">${esc(f.title)} — ${money(f)}</option>`).join(''); }
async function loadCatalog(){try{const r=await fetch('/api/catalog'); if(!r.ok)throw Error(); CATALOG=await r.json(); render();}catch(e){document.getElementById('homeGrid').innerHTML='<div class="notice">Impossible de charger le catalogue. Vérifiez que le serveur est démarré.</div>';}}
function openFilm(id){selectedFilm=CATALOG.films.find(f=>f.id===id); if(!selectedFilm)return; $('#modalPoster').src=selectedFilm.poster;$('#modalTitle').textContent=selectedFilm.title;$('#modalDesc').textContent=selectedFilm.description;$('#modalPrice').textContent=money(selectedFilm);$('#filmModal').classList.remove('hidden');}
function closeModal(){$('#filmModal').classList.add('hidden');}
function choosePayment(){closeModal();$('#paymentFilm').value=selectedFilm.id;show('payment');}
async function paymentDemo(){const f=CATALOG.films.find(x=>x.id===$('#paymentFilm').value); const msg=$('#paymsg'); try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filmId:f.id,provider:document.querySelector('.method.selected')?.dataset.provider||'pending',customer:{}})}); const j=await r.json(); if(!r.ok)throw Error(j.error); msg.className='notice';msg.innerHTML=`Commande <b>${j.order.id.slice(0,8)}</b> créée pour <b>${money(f)}</b>.<br>Le bouton de paiement réel sera connecté à MonCash/NatCash/carte. Après confirmation, le serveur créera automatiquement le code d’accès.`;}catch(e){msg.className='error';msg.textContent=e.message||'Erreur.';}}
async function verify(){const c=$('#code').value.trim().toUpperCase(),msg=$('#accessMsg'); try{const r=await fetch('/api/access/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:c})});const j=await r.json();if(!r.ok||!j.valid)throw Error(j.error||'Code invalide'); msg.className='success';msg.textContent='✓ Code valide. Accès autorisé.';selectedFilm=j.film;$('#watchTitle').textContent='🎬 '+j.film.title; const box=document.querySelector('.player'); if(j.film.videoUrl)box.innerHTML=`<video controls playsinline style="width:100%;max-height:70vh" src="${esc(j.film.videoUrl)}"></video><div class="watermark">HYBRID WOOD • ACCÈS PROTÉGÉ</div>`; else box.innerHTML='<div style="text-align:center">Accès autorisé.<br><small>Le lien vidéo sécurisé sera servi ici lorsque le film sera publié.</small></div>'; show('watch');}catch(e){msg.className='error';msg.textContent='✕ '+e.message;}}
document.addEventListener('DOMContentLoaded',()=>{loadCatalog();$('#year').textContent=new Date().getFullYear();$('#filmModal').addEventListener('click',e=>{if(e.target.id==='filmModal')closeModal();});});
